FROM debian:bookworm-slim AS base

FROM base AS builder

ENV SALT_VERSION="3007.1"
ENV PYTHONPATH="/workdir:/code/salt"

RUN apt-get update -y &&\
    apt-get -y --no-install-recommends install curl ca-certificates build-essential python3-dev python3-venv libffi-dev git xz-utils &&\
    mkdir /code && mkdir /install && mkdir /workdir &&\
    cd /code && git clone  https://github.com/saltstack/salt.git && cd /code/salt && git checkout v${SALT_VERSION} &&\
    python3 -m venv /install && . /install/bin/activate && pip3 install pyzmq PyYAML pycrypto msgpack jinja2 psutil futures tornado &&\
    cd /code && pip install -e ./salt
